[tool.poetry]
name = "fastapi-project"
version = "0.1.0"
description = ""
authors = ["ajaypawar22112001 <ajay.pawar@reversebits.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.11"
alembic = "^1.15.1"
pydantic-settings = "^2.8.1"
asyncpg = "^0.30.0"
sqlmodel = "^0.0.23"
python-dotenv = "^1.0.1"
sendgrid = "^6.11.0"
uvicorn = "^0.34.0"
python-jose = "^3.4.0"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
